name: rotom_phone
description: My own implementation of Pokedex.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Service locator
  get_it: ^5.0.0
  # Para utilziar el objeto Either
  dartz: ^0.9.1
  # Nos permite comparar varias instancias de un objeto
  equatable: ^1.2.5
  # Verificar si el usuario tiene acceso a internet
  data_connection_checker: ^0.3.4
  # Consumir APIs remotas
  http: ^0.12.2
  # Local Shared Preferences
  shared_preferences: ^0.5.10
  # Dependencia para usar state management con BloC y Cubit
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  # Local noSQL DB con Hive
  hive: ^1.4.4+1
  # Hive optimizado para flutter
  hive_flutter: ^0.3.1
  # Para cachear las imagenes
  cached_network_image: ^2.5.0
   # imagenes SVG
  flutter_svg: ^0.19.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4
  mockito: ^4.1.0
  flutter_coverage_badge: ^0.0.1+1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/white_pokeball.png
    - assets/images/pokeball_filled.png
    - assets/images/rotom_phone_icon.png
    - assets/images/pokeball_header.png
    - assets/images/types/poison.svg
    - assets/images/types/water.svg
    - assets/images/types/grass.svg
    - assets/images/types/bug.svg
    - assets/images/types/dark.svg
    - assets/images/types/dragon.svg
    - assets/images/types/electric.svg
    - assets/images/types/fairy.svg
    - assets/images/types/fighting.svg
    - assets/images/types/fire.svg
    - assets/images/types/flying.svg
    - assets/images/types/ghost.svg
    - assets/images/types/ice.svg
    - assets/images/types/ground.svg
    - assets/images/types/normal.svg
    - assets/images/types/steel.svg
    - assets/images/types/psychic.svg
    - assets/images/types/rock.svg
    - assets/images/about_menu.svg
    - assets/images/stats_menu.svg
    - assets/images/moves_menu.svg

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
